name:                nmap
version:             0.1.0.0
github:              "github.com/haskell-nmap"
license:             BSD3
author:              "Max Harley"
maintainer:          "maxh@maxh.io"
copyright:           "2020 Max Harley"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Nmap

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

  dependencies:
    - hxt
    - containers
    - text
    - html-entity
    - directory
    - process
    - filepath
    - random

executables:
  nmap-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - nmap
    - hxt
    - containers

tests:
  nmap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nmap
    - hspec
