resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/24.yaml

packages:
- .

extra-deps:
    - hxt-9.3.1.18
    - hspec-2.7.4
    - MissingH-1.4.3.0
    - html-entity-0.1.3.0
    - process-1.6.9.0
